
services:
  sqledge:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: azure-sql-edge
    mem_limit: 4g
    shm_size: 1g
    restart: unless-stopped
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "pp4sw0rd#s3c0r3"
      MSSQL_AGENT_ENABLED: "false"  # No necesario en desarrollo
    volumes:
      - sql_data:/var/opt/mssql
      - ./init-dev.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  sql_data:
