version: '3.6'

services:
  gitlab:
    image: gitlab/gitlab-ce:16.11.6-ce.0
    container_name: gitlab
    restart: no
    hostname: 'mi-windows.local'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://mi-windows.local'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - '80:80'
      - '443:443'
      - '2224:22'
    volumes:
      - 'gitlab-config:/etc/gitlab'
      - 'gitlab-logs:/var/log/gitlab'
      - 'gitlab-data:/var/opt/gitlab'

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
