services:
    mysql:
        #platform: linux/x86_64
        image: mysql:8.4
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: app_test
            MYSQL_USER: app_user
            MYSQL_PASSWORD: password
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'mysql8-data:/var/lib/mysql'
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-ppassword"]
            retries: 3
            timeout: 5s
volumes:
    mysql8-data:
      driver: local