services:
  web:
    image: odoo:18.0
    depends_on:
      - dbpgl
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - /Users/wilmertezen/Developer/idocker/odoo/config:/etc/odoo
      - /Users/wilmertezen/Developer/idocker/odoo/extra-addons:/mnt/extra-addons
    environment:
      - HOST=dbpgl
      - USER=odoo
      - PASSWORD=odoo
  dbpgl:
    platform: linux/x86_64
    image: postgres:13
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

volumes:
  odoo-web-data:
  odoo-db-data:
