services:
  sqlserver:
    image: mcr.microsoft.com/mssql/rhel/server:2019-latest # Imagen de SQL Server
    container_name: sqlserver
    ports:
      - "1433:1433" # Mapea el puerto 1433
    environment:
      ACCEPT_EULA: "Y" # Acepta el acuerdo de licencia
      SA_PASSWORD: "pp4sw0rd#s3c0r3" # Contraseña para el usuario sa
    volumes:
      - sql_data:/var/opt/mssql # Volumen para persistencia de datos
    restart: no # Reinicia automáticamente si el contenedor se detiene

volumes:
  sql_data:
    driver: local # Usa el driver local para persistencia


# NOTE
# CREATE DATABASE
# docker exec -it CONTAINERID-HERE /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P pp4sw0rd#s3c0r3 -C -Q "CREATE DATABASE TEST;"